name: Full Build

on: [push]

# Reduced compile matrix to single os and do multiple compiles in a single run to reduce minute usage

jobs:
  Linux:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MSF_REPO_ACCESS }}
        submodules: recursive
    - name: setup
      run: |
        chmod +x *.sh
        chmod -R +x bin/*
    - name: install dependencies
      run: ./install_dependencies.sh
    - name: generate projects
      run: ./generate_projects.sh
    - name: compile and test debug linux clang
      run: ./build_and_run_tests.sh debug linux clang
    - name: compile and test release linux clang
      run: ./build_and_run_tests.sh release linux clang
    - name: compile and test debug linux gcc
      run: ./build_and_run_tests.sh debug linux gcc
    - name: compile and test release linux gcc
      run: ./build_and_run_tests.sh release linux gcc
    - name: compile and test debug_validation linux clang
      run: ./build_and_run_tests.sh debug_validation linux clang
    - name: compile and test release_validation linux clang
      run: ./build_and_run_tests.sh release_validation linux clang
    - name: compile and test debug_validation linux gcc
      run: ./build_and_run_tests.sh debug_validation linux gcc
    - name: compile and test release_validation linux gcc
      run: ./build_and_run_tests.sh release_validation linux gcc

  Mac_OSX:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MSF_REPO_ACCESS }}
        submodules: recursive
    - name: setup
      run: |
        chmod +x *.sh
        chmod -R +x bin/*
    - name: generate projects
      run: ./generate_projects_osx.sh
    - name: compile and test debug
      run: ./build_and_run_tests.sh debug mac
    - name: compile and test release
      run: ./build_and_run_tests.sh release mac
    - name: compile and test debug_validation
      run: ./build_and_run_tests.sh debug_validation mac
    - name: compile and test release_validation
      run: ./build_and_run_tests.sh release_validation mac
  Windows:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      SLN_PATH: projects\modernstringformatsolution_win64_vs2019.sln
      SLN_PATH32: projects\modernstringformatsolution_win32_vs2019.sln
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MSF_REPO_ACCESS }}
        submodules: recursive
    - name: generate projects
      run: .\generate_projects.bat
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1      
    - name: compile and test debug 64
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Debug
        .\.temp\bin\modernstringformatproject_win64_vs2019_debug.exe
    - name: compile and test release 64
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Release
        .\.temp\bin\modernstringformatproject_win64_vs2019_release.exe 
    - name: compile and test debug 32
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH32%" /p:Configuration=Debug
        .\.temp\bin\modernstringformatproject_win32_vs2019_debug.exe
    - name: compile and test release 32
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH32%" /p:Configuration=Release
        .\.temp\bin\modernstringformatproject_win32_vs2019_release.exe 
    - name: compile and test debug validation 64
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Debug_Validation
        .\.temp\bin\modernstringformatproject_win64_vs2019_debug_validation.exe
    - name: compile and test release validation 64
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Release_Validation
        .\.temp\bin\modernstringformatproject_win64_vs2019_release_validation.exe 
    - name: compile and test debug validation 32
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH32%" /p:Configuration=Debug_Validation
        .\.temp\bin\modernstringformatproject_win32_vs2019_debug_validation.exe
    - name: compile and test release validation 32
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH32%" /p:Configuration=Release_Validation
        .\.temp\bin\modernstringformatproject_win32_vs2019_release_validation.exe 
