name: Full Build

on: [push]

# Reduced compile matrix to single os and do multiple compiles in a single run to reduce minute usage

jobs:
  Linux:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MSF_REPO_ACCESS }}
        submodules: recursive
    - name: setup
      run: |
        chmod +x *.sh
    - name: generate projects
      run: ./generate_projects.sh
    - name: compile and test debug linux clang
      run: ./build_and_run_tests.sh debug linux clang
    - name: compile and test release linux clang
      run: ./build_and_run_tests.sh release linux clang
    - name: compile and test debug linux gcc
      run: ./build_and_run_tests.sh debug linux gcc
    - name: compile and test release linux gcc
      run: ./build_and_run_tests.sh release linux gcc
      # todo: clang crashes and gcc 11 isn't available
#    - name: compile and test debug_validation linux clang
#      run: ./build_and_run_tests.sh debug_validation linux clang
#    - name: compile and test release_validation linux clang
#      run: ./build_and_run_tests.sh release_validation linux clang
#    - name: compile and test debug_validation linux gcc
#      run: ./build_and_run_tests.sh debug_validation linux gcc
#    - name: compile and test release_validation linux gcc
#      run: ./build_and_run_tests.sh release_validation linux gcc

  Mac_OSX:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MSF_REPO_ACCESS }}
        submodules: recursive
    - name: setup
      run: |
        chmod +x *.sh
    - name: generate projects
      run: ./generate_projects_osx.sh
    - name: compile and test debug
      run: ./build_and_run_tests.sh debug mac
    - name: compile and test release
      run: ./build_and_run_tests.sh release mac
      # todo: clang crashes and I'm not building gcc on mac... yet
#    - name: compile and test debug_validation
#      run: ./build_and_run_tests.sh debug_validation mac
#    - name: compile and test release_validation
#      run: ./build_and_run_tests.sh release_validation mac
  Windows:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      SLN_PATH: projects\modernstringformatsolution_vs2022.sln
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MSF_REPO_ACCESS }}
        submodules: recursive
    - name: generate projects
      run: .\generate_projects.bat
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1      
    - name: compile and test debug 64
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Debug /p:Platform=x64
        .\.temp\bin\modernstringformatproject_vs2022_win64_debug.exe
    - name: compile and test release 64
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Release /p:Platform=x64
        .\.temp\bin\modernstringformatproject_vs2022_win64_release.exe 
    - name: compile and test debug 32
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Debug /p:Platform=win32
        .\.temp\bin\modernstringformatproject_vs2022_win32_debug.exe
    - name: compile and test release 32
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Release /p:Platform=win32
        .\.temp\bin\modernstringformatproject_vs2022_win32_release.exe 
    - name: compile and test debug validation 64
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Debug_Validation /p:Platform=x64
        .\.temp\bin\modernstringformatproject_vs2022_win64_debug_validation.exe
    - name: compile and test release validation 64
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Release_Validation /p:Platform=x64
        .\.temp\bin\modernstringformatproject_vs2022_win64_release_validation.exe 
    - name: compile and test debug validation 32
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Debug_Validation /p:Platform=win32
        .\.temp\bin\modernstringformatproject_vs2022_win32_debug_validation.exe
    - name: compile and test release validation 32
      shell: cmd
      run: |
        msbuild.exe "%SLN_PATH%" /p:Configuration=Release_Validation /p:Platform=win32
        .\.temp\bin\modernstringformatproject_vs2022_win32_release_validation.exe 
